// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<void>;

export function LocalIP():Promise<string>;

export function ScanPeers():Promise<Array<string>>;
