// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['ui']['UI']['Connect'](arg1);
}

export function LocalIP() {
  return window['go']['ui']['UI']['LocalIP']();
}

export function ScanPeers() {
  return window['go']['ui']['UI']['ScanPeers']();
}
