// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestFrame() {
  return window['go']['main']['Stream']['GetLatestFrame']();
}

export function Start(arg1) {
  return window['go']['main']['Stream']['Start'](arg1);
}
