// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestFrame():Promise<Array<number>>;

export function Start(arg1:string):Promise<void>;
